import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Vanessa Torres',
      email: 'admin@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John Doe',
      email: 'user@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'DNA J-HOPE',
      slug: 'dna-jhope',
      category: 'Prints',
      size: 'A5',
      image: '/images/desenhos_2018_anime_jhope.jpg',
      price: 50,
      countInStock: 20,
      description: '2018 Anime Style: DNA J-HOPE',
    },
    {
      name: 'DNA RM',
      slug: 'dna-rm',
      category: 'Prints',
      size: 'A5',
      image: '/images/desenhos_2018_anime_rm.jpg',
      price: 50,
      countInStock: 20,
      description: '2018 Anime Style: DNA RM',
    },
    {
      name: 'DNA SUGA',
      slug: 'dna-suga',
      category: 'Prints',
      size: 'A5',
      image: '/images/desenhos_2018_anime_suga.jpg',
      price: 50,
      countInStock: 20,
      description: '2018 Anime Style: DNA SUGA',
    },
    {
      name: '3JS: J-HOPE',
      slug: '3js-jhope',
      category: 'Prints',
      size: 'A4',
      image: '/images/desenhos_2018_jhope.jpg',
      price: 70,
      countInStock: 20,
      description: '2018 3JS, Dance Line: J-HOPE',
    },
    {
      name: '3JS: JUNGKOOK',
      slug: '3js-jk',
      category: 'Prints',
      size: 'A4',
      image: '/images/desenhos_2018_jk.jpg',
      price: 70,
      countInStock: 20,
      description: '2018 3JS, Dance Line: JUNGKOOK',
    },
    {
      name: '3JS: JIMIN',
      slug: '3js-jm',
      category: 'Prints',
      size: 'A4',
      image: '/images/desenhos_2018_jm.jpg',
      price: 70,
      countInStock: 20,
      description: '2018 3JS, Dance Line: JIMIN',
    },
    {
      name: 'Gemstone: Rubi',
      slug: 'rubi-v',
      category: 'Prints',
      size: 'A4',
      image: '/images/desenhos_2019_rubi_v.jpg',
      price: 70,
      countInStock: 20,
      description: '2019 Gemstone: Rubi Taehyung',
    },
    {
      name: 'Gemstone: Sapphire',
      slug: 'sapphire-jm',
      category: 'Prints',
      size: 'A4',
      image: '/images/desenhos_2019_sapphire_jm.jpg',
      price: 70,
      countInStock: 20,
      description: '2019 Gemstone: Sapphire Jimin',
    },
    {
      name: 'DPR LIVE',
      slug: 'dpr-live',
      category: 'Prints',
      size: 'A4',
      image: '/images/desenhos_2021_DPR.jpg',
      price: 70,
      countInStock: 20,
      description: '2021 DPR LIVE',
    },
  ],
};
export default data;
